# Generated by Django 2.0.3 on 2018-04-02 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=250)),
                ('description_small', models.TextField()),
                ('description_long', models.TextField()),
                ('user_rating', models.PositiveSmallIntegerField()),
                ('keyword1', models.CharField(max_length=250)),
                ('keyword2', models.CharField(max_length=250)),
                ('keyword3', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=15)),
                ('validity', models.DateField()),
                ('street', models.CharField(max_length=550)),
                ('city', models.CharField(max_length=550)),
                ('country', models.CharField(max_length=550)),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('deal_logo', models.CharField(default='xxx', max_length=1000)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.Area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=550)),
                ('lastName', models.CharField(max_length=550)),
                ('email', models.CharField(max_length=550)),
                ('password', models.CharField(max_length=550)),
                ('type', models.CharField(max_length=550)),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.User'),
        ),
    ]
