# Generated by Django 2.0.3 on 2018-04-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_auto_20180406_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='user_rating',
        ),
    ]
