# Generated by Django 2.0.3 on 2018-04-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_remove_deal_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='user_rating',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
