# Generated by Django 2.0.3 on 2018-04-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_auto_20180408_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='user_rating',
        ),
    ]
