# Generated by Django 2.0.3 on 2018-04-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_remove_deal_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='country',
            field=models.CharField(default='Bangladesh', max_length=550),
        ),
    ]
