# Generated by Django 2.0.4 on 2018-04-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0009_auto_20180408_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
